steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dtumlops-404710/mtrainimage', '-f', 'Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dtumlops-404710/mtrainimage']

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/dtumlops-404710/apiimage', '-f', 'api.Dockerfile', '.']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/dtumlops-404710/apiimage']
