# config_gpu.yaml
#workerPoolSpecs:
#    machineSpec:
#        machineType: n1-standard-8
#        acceleratorType: NVIDIA_TESLA_T4
#        acceleratorCount: 1
#    replicaCount: 1
#    containerSpec:
#        imageUri: gcr.io/dtumlops-404710/mtrainimage


# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/dtumlops-404710/mtrainimage



