wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1700510553.09404
    t:
      1:
      - 1
      - 5
      - 41
      - 50
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.9.18
      5: 0.16.0
      8:
      - 2
      - 5
      13: darwin-arm64
