wandb_version: 1

learning_rate:
  desc: null
  value: 0.02
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: CIFAR-100
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1700510274.424924
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.9.18
      5: 0.16.0
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
